hvr/head.hackage

- patches/doctest-0.11.4.patch
I've verified that this compiles with ghc-8.2.1 and ghc-head
> Add patch for doctest-0.11.4

- patches/happy-1.19.8.patch
- patches/hashtables-1.2.2.1.patch
- scripts/head.hackage.sh
- scripts/unpack.sh
I'd much prefer to simply specify the path on the command line.
> head.hackage.sh: Don't hardcode GHC path

- patches/gloss-rendering-1.11.1.1.patch
> Add patch for gloss-rendering

- scripts/make-patch.sh
Creating patches is a bit tiresome, so here's some glue to make it a bit easier.
You basically need
```
echo "HEAD_HACKAGE_CLONE_PATH=\$HOME/path/to/head.hackage" > ~/.head.hackage
```
> Adds patch-tool

- patches/psqueues-0.2.4.0.patch
Taken from https://github.com/jaspervdj/psqueues/pull/24.
> Add patch for psqueues

- patches/accelerate-1.1.1.0.patch
Loosely based on https://github.com/AccelerateHS/accelerate/pull/416.
> Add patch for accelerate

- patches/llvm-hs-5.1.3.patch
- patches/llvm-hs-pure-5.1.2.patch
Adapted from https://github.com/llvm-hs/llvm-hs/pull/175.
> Add patches for llvm-hs and llvm-hs-pure

- patches/language-c-0.7.1.patch
Taken from https://github.com/visq/language-c/pull/45.
> Add patch for language-c

- patches/accelerate-llvm-1.1.0.0.patch
- patches/accelerate-llvm-native-1.1.0.1.patch
Based on https://github.com/AccelerateHS/accelerate-llvm/pull/30.
> Add patches for accelerate-llvm and accelerate-llvm-native

- patches/boxes-0.1.4.patch
- patches/monadplus-1.4.2.patch
These were needed to build [Agda](https://github.com/agda/agda/issues/2878).
Taken from:
* https://github.com/treeowl/boxes/pull/30
* https://github.com/hanshoglund/monadplus/pull/3
> Add patches for boxes and monadplus

- patches/HsOpenSSL-0.11.4.11.patch
- patches/css-text-0.1.2.2.patch
- patches/http-client-0.5.8.patch
- patches/language-javascript-0.6.0.10.patch
- patches/websockets-0.12.3.1.patch
Various things I needed to build `purescript`. Taken from:
* https://github.com/vshabanov/HsOpenSSL/pull/35
* https://github.com/yesodweb/css-text/pull/13
* https://github.com/snoyberg/http-client/pull/320
* https://github.com/erikd/language-javascript/pull/65
* https://github.com/jaspervdj/websockets/pull/164
> Assorted patches for purescript dependencies

- patches/non-negative-0.1.1.2.patch
- patches/numeric-prelude-0.4.2.patch
- patches/protocol-buffers-2.4.6.patch
- patches/storable-record-0.0.3.1.patch
Various things I needed with building the `lol` libraries. (The `protocol-buffers` patch is taken from https://github.com/k-bx/protocol-buffers/pull/57.)
> Assorted patches for lol dependencies

- patches/JuicyPixels-3.2.9.3.patch
- patches/MemoTrie-0.6.8.patch
- patches/cubicbezier-0.6.0.4.patch
- patches/diagrams-canvas-1.4.patch
- patches/diagrams-contrib-1.4.1.patch
- patches/diagrams-core-1.4.0.1.patch
- patches/diagrams-lib-1.4.2.patch
- patches/diagrams-postscript-1.4.patch
- patches/diagrams-svg-1.4.1.1.patch
- patches/monoid-extras-0.4.2.patch
- patches/svg-builder-0.1.0.2.patch
- patches/vector-space-0.12.patch
Taken from:
* https://github.com/Twinside/Juicy.Pixels/pull/150
* https://github.com/conal/MemoTrie/pull/16
* https://github.com/kuribas/cubicbezier/pull/8
* https://github.com/diagrams/diagrams-canvas/pull/18
* https://github.com/diagrams/diagrams-contrib/pull/71
* https://github.com/diagrams/diagrams-core/pull/95
* https://github.com/diagrams/diagrams-lib/pull/308
* https://github.com/diagrams/diagrams-postscript/pull/25
* https://github.com/diagrams/diagrams-svg/pull/101
* https://github.com/diagrams/monoid-extras/pull/34
* https://github.com/diagrams/svg-builder/pull/4
* https://github.com/conal/vector-space/pull/23
> Assorted patches for diagrams

- patches/OneTuple-0.2.1.patch
- patches/inline-c-0.6.0.5.patch
- patches/language-java-0.2.8.patch
- patches/map-syntax-0.2.0.2.patch
Taken from:
* https://github.com/mightybyte/map-syntax/pull/11
* https://github.com/vincenthz/language-java/pull/63
* https://github.com/fpco/inline-c/pull/66
> An assortment of patches

- patches/fast-logger-2.4.10.patch
- patches/http-api-data-0.3.7.2.patch
- patches/shakespeare-2.0.14.1.patch
- patches/yesod-core-1.6.0.patch
- patches/yesod-form-1.6.0.patch
- patches/yesod-test-1.6.0.patch
Various patches I needed to get `yesod` building. Taken from:
* https://github.com/fizruk/http-api-data/pull/68
* https://github.com/yesodweb/shakespeare/pull/216
* https://github.com/yesodweb/yesod/pull/1484
* https://github.com/kazu-yamamoto/logger/pull/155
> yesod patches

- patches/diagrams-cairo-1.4.patch
- patches/diagrams-contrib-1.4.2.1.patch
- patches/gtk2hs-buildtools-0.13.3.1.patch
Based off of:
* https://github.com/gtk2hs/gtk2hs/pull/231 and https://github.com/gtk2hs/gtk2hs/pull/233
* https://github.com/diagrams/diagrams-contrib/pull/74
* https://github.com/diagrams/diagrams-cairo/pull/70
> diagrams, gtk patches

- patches/ekg-core-0.1.1.3.patch
- patches/snap-server-1.0.3.3.patch
Taken from:
* https://github.com/tibbe/ekg-core/pull/23
* https://github.com/snapframework/snap-server/pull/106
> ekg-core, snap-server patches

- patches/contravariant-1.4.1.patch
Based on the patch from https://github.com/ekmett/contravariant/pull/45.
> Add contravariant patch

- patches/repa-3.4.1.3.patch
- patches/repa-algorithms-3.4.1.2.patch
- patches/repa-examples-3.4.1.1.patch
These adapt some packages in the `repa`verse to the removal of the `-Odph` flag from GHC.
> repa patches

- patches/vector-algorithms-0.7.0.1.cabal
Include the revised `vector-algorithms-0.7.0.1.cabal` file so as to avoid #65.
> Work around #65

- README.md
- scripts/patch-tool
* Rename it to `patch-tool`. 
* Add a mode to cull old patches
* Use a nix-compatible hash-bang
* A bit of documentation
> Clean up patch-tool

- patches/c2hs-0.28.5.cabal
- patches/gtk2hs-buildtools-0.13.4.0.cabal
- patches/haskell-src-exts-1.20.2.cabal
- patches/snap-1.1.1.0.cabal
- patches/yi-core-0.18.0.cabal
- patches/yi-keymap-emacs-0.18.0.cabal
- patches/yi-keymap-vim-0.18.0.cabal
- patches/yi-mode-javascript-0.18.0.cabal
8 more packages which need `NoMonadFailDesugaring`.
> Some more NoMonadFailDesugaring tweaks

- patches/MissingH-1.4.0.1.cabal
`MissingH` needs to have `MonadFailDesugaring` disabled.
> Add MissingH patch

- README.md
- patches/exhaustive-1.1.7.patch
- patches/generic-deriving-1.12.2.cabal
- patches/generic-deriving-1.12.2.patch
- patches/io-choice-0.0.6.patch
- patches/lens-4.17.patch
- patches/persistent-template-2.5.4.cabal
- patches/persistent-template-2.5.4.patch
- patches/safecopy-0.9.4.1.patch
- patches/store-0.5.0.1.patch
- patches/th-abstraction-0.2.8.0.cabal
- patches/th-abstraction-0.2.8.0.patch
- patches/th-data-compat-0.0.2.7.patch
- patches/th-utilities-0.2.0.1.patch
- patches/true-name-0.1.0.3.patch
- patches/vector-th-unbox-0.2.1.6.patch
> template-haskell-2.15–related patches

- scripts/generate-nix-overrides.hs
> Properly handle .cabal files as well as patches (by mpickering)

- patches/sop-core-0.4.0.0.patch
- patches/vinyl-0.11.0.patch
A follow-up to 8db44df47e6ca07ea2f8140dfa672d0f9f542ac7. More packages that were broken due to GHC proposal 24.
> Further adaption to GHC proposal 24

- README.md
- scripts/patch-tool
This makes `patch-tool` a bit more robust and teaches it to account for cabal file updates.
> Various fixes and a bit of documentation for patch-tool
