hvr/head.hackage

- patches/llvm-hs-5.1.0.patch
llvm-hs uses a custom `Setup.hs` which needs to be adapted to the recent `FlagAssignment` change in cabal.
> llvm-hs 5.1.0: Cabal >= 2.1 compatibility

- patches/colour-2.3.3.patch
The current patch results into the following error with GHC 8.2.1:
```
Data/Colour/RGBSpace.hs:112:21: error:
Not in scope: type constructor or class ‘Semigroup’
|
112 | instance (Num a) => Semigroup (TransferFunction a) where
|                     ^^^^^^^^^
```
I think the policy is that this should work, too.
I based the new patch on the old patch and just replaced the `Data.Monoid` import with `Data.Semigroup`.
> colour 2.3.3: GHC < 8.3 compatibility

- patches/constraints-0.9.1.patch
`GHC.TypeLits` recently added `Div` and `Mod` which interfere with `Data.Constraints.Nat`, this commit hides them from the import.
> Hide Div / Mod from GHC.TypeLits

- patches/criterion-1.2.6.0.patch
- patches/haskell-src-exts-1.20.1.patch
- patches/simple-reflect-0.3.2.patch
I needed these when trying to build `lens`'s test suite and benchmarks on GHC 8.4.
> Add patches for criterion, haskell-src-exts, and simple-reflect

- scripts/README.md
- scripts/generate-nix-overrides.hs
- scripts/overrides.nix
This is a modified version of the script originally written by @peti and requested by @bgamari.
There are a few changes
1. Patches are fetched once when the overrides are generated and stored in the nix-store rather than from the github repo. This allows the source of the patches to be more flexible.
2. I added a wrapper which builds the `patches.nix` file for you so you can just add a patch to `patches` and it will regenerate the overrides.
> Add instructions and scripts for using the repo on nix

- README.md
- scripts/conduit-1.2.12.1.patch
- scripts/haskell-src-exts-util-0.2.1.2.patch
- scripts/streaming-0.2.0.0.patch
I needed these recently when upgrading `machines` and `rcu` to GHC 8.4.1-alpha.
> Add patches for conduit, haskell-src-exts-util, and streaming

- patches/bytestring-trie-0.2.4.1.patch
- patches/critbit-0.2.0.0.patch
I needed these for the examples in `criterion`.
> Add patches for bytestring-trie and critbit

- patches/vinyl-0.7.0.patch
It seems it's been affected by Semigroup superclass migration
Presumably this could just be an upstream patch
> Add a patch for vinyl-0.7.0

- scripts/generate-nix-overrides.hs
- scripts/overrides.nix
* Don't try to apply patches to built in, fixed packages which come with the compiler
* Remove use of deprecated `ensureDir`.
> Fix nix scripts

- patches/singletons-2.4.1.patch
- patches/th-orphans-0.13.5.patch
This allows `th-orphans-0.13.5` and `singletons-2.4.1` to build under `template-haskell-2.14`.
> Two packages broken under template-haskell-2.14

- patches/entropy-0.4.1.1.patch
Also incorporates a `Setup.hs` fix from https://github.com/TomMD/entropy/pull/39.
> Patch entropy to work with unix-2.8

- patches/doctest-0.15.0.patch
Trees That Grow changed the AST, demanding further tweaks to `doctest` to make it build on GHC HEAD.
> Adapt doctest-0.15.0 patch post-TTG

- patches/bytestring-mmap-0.2.2.patch
- patches/shake-0.16.4.patch
The `shake` patch is adapted from [this commit](https://github.com/ndmitchell/shake/commit/873f0746b4dcc2d5294b3181d986f658b98ec59a#diff-60a311e0dc79ef3464236696fc2df01b).
> Patch bytestring-mmap, shake to work with unix-2.8

- patches/tasty-1.1.0.1.patch
In http://git.haskell.org/ghc.git/commit/b67e8a3f107f7e7b2cefb526a5f956a4a3abc852, `Data.Monoid` gained the `Ap` newtype, which conflicts with a similarly named type in `tasty`. This patch adds the necessary CPP to work around the issue.
> Allow tasty to build with base-4.12

- patches/doctest-0.15.0.patch
- patches/vector-algorithms-0.7.0.1.patch
(Split off from #61.)
`doctest` needs to be adapted to the removal of the `HsDocString` constructor.
`vector-algorithms` needs to be adapted to the removal of Data Parallel Haskell (and thus the `-Odph` flag's removal).
> Adapt doctest and vector-algorithms to build with the lastest GHC HEAD

- patches/basement-0.0.7.patch
- patches/constraints-0.10.patch
- patches/memory-0.14.16.patch
- patches/reflection-2.1.3.patch
- patches/singletons-2.4.1.patch
- patches/tasty-1.1.0.2.patch
Now that GHC 8.6.1-alpha1 is out, I've cooked up a fresh batch of patches:
* Adapting to `StarIsType`:
* `basement`
* `constraints`
* `memory`
* `reflection`
* `singletons`
* Adapting to `Data.Monoid.Ap`
* `tasty`
> Some GHC 8.6.1 patches

- patches/Unixutils-1.54.1.patch
- patches/accelerate-1.2.0.0.patch
- patches/cipher-aes128-0.7.0.3.patch
- patches/hslogger-1.2.10.patch
- patches/ixset-1.1.patch
- patches/ixset-typed-0.4.patch
- patches/language-c-0.8.1.patch
- patches/numtype-dk-0.5.0.1.patch
- patches/protolude-0.2.2.patch
Categorized by the reasons they break on GHC 8.6.1:
* `UndecidableInstances` is picker on 8.6
* `accelerate`
* `Cabal-2.5` API changes
* `cipher-aes128`
* `containers-0.6` API changes
* `ixset`
* `ixset-typed`
* `language-c`
* `StarIsType` and `stm-2.5` API changes
* `numtype-dk`
* `protolude`
* `unix-2.8` API changes
* `Unixutils`
> Even more GHC 8.6.1-related patches

- patches/exact-pi-0.4.1.3.patch
- patches/multiset-0.3.4.patch
- patches/vector-space-0.13.patch
* `exact-pi` (`StarIsType`)
* `multiset` (`containers-0.6` API changes)
* `vector-space` (`UndecidableInstances` is pickier)
> Three more GHC 8.6-related patches

- patches/primitive-0.6.4.0.patch
This is holding up Haddock's CI for `ghc-head`.
cc @sjakobi @alexbiehl.
> primitive 'GHC.Prim' -> 'GHC.Exts'

- patches/cassava-0.5.1.0.cabal
- patches/primitive-0.6.4.0.cabal
The most recent versions of `cassava` and `primitive` on Hackage actually do support GHC HEAD, but only because of revisions. Due to #65, `head.hackage` does not take these revisions into account and falls back on the original `.cabal` files with out-of-date bounds on `base` (for `primitive`) and `containers` (for `cassva`). As a workaround, this puts the most recent `.cabal` files (including revisions) for `cassava`/`primitive` into `head.hackage`.
> Update .cabal files for cassava, primitive

- patches/th-abstraction-0.2.10.0.patch
- patches/th-abstraction-0.2.9.0.patch
A new version of `th-abstraction` (0.2.10.0) was released, and just like version 0.2.8.0, it needs to be patched to support GHC HEAD.
> Add patch for th-abstraction-0.2.10.0

- patches/cabal-doctest-1.0.6.patch
`Cabal-2.5.0.0` has made some changed to `libName`, which prevents `cabal-doctest-1.0.6` from building without some surgery.
> Patch cabal-doctest-1.0.6 to work with Cabal-2.5.*

- patches/singleton-nats-0.4.2.patch
- patches/singletons-2.5.1.patch
- patches/th-desugar-1.9.patch
These packages in particular were harshly affected by changes to Template Haskell introduced in GHC 8.8, so they need a bit of surgery in certain places in order to be made to compile. Some particulars:
* GHC 8.8 changes the API for `TySynInstD`, `TySynEqn`, `DataInstD`, `NewtypeInstD`, and `RuleP`, so I had to add quite a bit of CPP to `th-desugar` to make everything work on 8.8. (Refer to the original commit that I took this patch from, https://github.com/goldfirere/th-desugar/commit/9b9a6f0bdb6becd3f5ae896ddb539069131f7ba0, for the full story.)
* Due to [GHC Trac #16133](https://ghc.haskell.org/trac/ghc/ticket/16133) being fixed, `singletons`-generated code now requires explicitly enabling the `TypeApplications` extension. (The generated code was always using `TypeApplications` under …
> Add patches for th-desugar-1.9, singletons-2.5.1, and singleton-nats-0.4.2

- scripts/generate-nix-overrides.hs
- scripts/overrides.nix
..which is missing `contravariant` in Nixpkgs `master`.
Described in https://github.com/hvr/head.hackage/issues/94
> hs-generate-overrides:  fix aeson

- patches/th-abstraction-0.2.11.0.patch
This moves the `th-abstraction` patch to the latest Hackage version, 0.2.11.0.
> Migrate th-abstraction patch to version 0.2.11.0

- patches/constraints-0.10.1.patch
- patches/lens-4.17.patch
- patches/singleton-bool-0.1.4.cabal
- patches/singleton-bool-0.1.4.patch
GHC [proposal 24](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0024-no-kind-vars.rst) (Treat kind variables and type variables identically in `forall`) breaks a handful of libraries that implicitly quantify kind variables in a top-level `forall`, so these patches work around this.
> Adapt to GHC proposal 24

- patches/th-orphans-0.13.6.patch
`th-orphans` currently does not build on GHC HEAD due to mgsloan/th-orphans#27. It's not entirely clear how the library should be patched, but adding a partial `Lift Bytes` instance does the job for now.
> Patch th-orphans to work around https://github.com/mgsloan/th-orphans/issues/27

- patches/hpack-0.31.2.patch
- patches/persistent-template-2.6.0.patch
- patches/recursion-schemes-5.1.2.patch
- patches/yesod-core-1.6.13.patch
`hpack` needs some CPP to work with `Cabal-2.5`, while `persistent-template`, `recursion-schemes`, and `yesod-core` needs some CPP to work with `template-haskell-2.15`.
> Patch some packages to work with Cabal-2.5, template-haskell-2.15

- patches/lens-4.17.1.patch
One of the commits in the previous `lens-4.17` patch shipped with `lens-4.17.1`, so that part of the patch was removed.
> Migrate lens patch to version 4.17.1

- patches/singletons-2.5.1.patch
https://gitlab.haskell.org/ghc/ghc/commit/4ba73e00c4887b58d85131601a15d00608acaa60 changed the type of `Uniq` (in `template-haskell`) from `Int` to `Integer`, which breaks `singletons`. This work around the change accordingly with `fromIntegral`.
Patch taken from goldfirere/singletons#389.
> Adapt singletons-2.5.1 patch to GHC commit 4ba73e00

- patches/cabal-doctest-1.0.6.patch
In `Cabal-3.0.*`, `Distribution.Simple.BuildPaths` no longer exports `autogenModulesDir` and `Distribution.Simple.Utils` no longer exports `rewriteFile`, so guard them with the appropriate CPP.
> Update cabal-doctest patch to accommodate Cabal-3.0.* changes

- patches/ghc-paths-0.1.0.9.patch
`ghc-paths`' custom `Setup` script uses `rawSystemProgramStdoutConf`, which was removed in `Cabal-3.0.*` in favor of `getDbProgramOutput`.
> Patch ghc-paths-0.1.0.9 to work with Cabal-3.0.*
